services:
  api:
    build:
      context: .  # Корень проекта
      dockerfile: docker/Dockerfile
    container_name: api_referal_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/api_referal
      REDIS_URL: redis://redis:6379
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: api_referal_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_referal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: api_referal_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
